# Generated by Django 2.1.4 on 2020-04-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidskills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordsheet',
            name='cwid',
            field=models.CharField(default='pro2004', max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recordsheet',
            name='assignedprojects',
            field=models.ManyToManyField(blank=True, to='covidskills.Project'),
        ),
        migrations.AlterField(
            model_name='recordsheet',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recordsheet',
            name='fieldstrained',
            field=models.ManyToManyField(blank=True, to='covidskills.StudyField'),
        ),
        migrations.AlterField(
            model_name='recordsheet',
            name='recordname',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='recordsheet',
            name='skillsets',
            field=models.ManyToManyField(blank=True, to='covidskills.Skill'),
        ),
        migrations.AlterField(
            model_name='recordsheet',
            name='supervisor',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
