# Generated by Django 2.1.4 on 2020-04-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidskills', '0002_auto_20200402_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordsheet',
            name='bestnumber',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Best contact number'),
        ),
    ]
