# Generated by Django 2.1.4 on 2020-04-07 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidskills', '0003_auto_20200403_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('CO', 'Highest (COVID)'), ('HI', 'High'), ('ME', 'Medium'), ('LO', 'Low')], default='LO', max_length=2),
        ),
        migrations.AddField(
            model_name='project',
            name='projecttype',
            field=models.CharField(choices=[('OP', 'Operational'), ('CO', 'COVID related'), ('PR', 'Project')], default='OP', max_length=2),
        ),
        migrations.AddField(
            model_name='project',
            name='timeneeded',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of weeks needed'),
        ),
        migrations.AddField(
            model_name='recordsheet',
            name='deferdays',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Days each week that can be deferred'),
        ),
        migrations.AddField(
            model_name='recordsheet',
            name='deferimpact',
            field=models.TextField(blank=True, null=True, verbose_name='Impact of deferring work'),
        ),
        migrations.AddField(
            model_name='recordsheet',
            name='deferlimit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max weeks able to be deferred'),
        ),
        migrations.AddField(
            model_name='recordsheet',
            name='remotetime',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Days working remote (round up)'),
        ),
        migrations.AddField(
            model_name='recordsheet',
            name='strongskills',
            field=models.ManyToManyField(blank=True, db_table='db_strskills_employee', related_name='strskills', to='covidskills.Skill', verbose_name='Employee strong skills'),
        ),
        migrations.AlterField(
            model_name='project',
            name='detailurl',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='Project URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pi',
            field=models.CharField(max_length=128, verbose_name='Project lead/supervisor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectdefinition',
            field=models.TextField(verbose_name='Description of project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectname',
            field=models.CharField(max_length=64, verbose_name='Project name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skillsrequired',
            field=models.ManyToManyField(to='covidskills.Skill', verbose_name='Skills required'),
        ),
        migrations.AlterField(
            model_name='recordsheet',
            name='cwid',
            field=models.CharField(max_length=16, unique=True, verbose_name='CWID'),
        ),
        migrations.AlterField(
            model_name='recordsheet',
            name='fieldstrained',
            field=models.ManyToManyField(blank=True, to='covidskills.StudyField', verbose_name='Tertiary training'),
        ),
        migrations.AlterField(
            model_name='recordsheet',
            name='recordname',
            field=models.CharField(max_length=256, unique=True, verbose_name='Employee name'),
        ),
        migrations.AlterField(
            model_name='recordsheet',
            name='skillsets',
            field=models.ManyToManyField(blank=True, db_table='db_regskills_employee', related_name='regskills', to='covidskills.Skill', verbose_name='Employee skills'),
        ),
        migrations.AlterField(
            model_name='recordsheet',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='record_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skilldefinition',
            field=models.TextField(verbose_name='Skill definition'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skillname',
            field=models.CharField(max_length=64, verbose_name='Skill name'),
        ),
        migrations.AlterField(
            model_name='studyfield',
            name='fielddefinition',
            field=models.TextField(verbose_name='Description of field'),
        ),
        migrations.AlterField(
            model_name='studyfield',
            name='fieldname',
            field=models.CharField(max_length=64, verbose_name='Name of field'),
        ),
    ]
