# Generated by Django 2.1.4 on 2020-04-08 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covidskills', '0004_auto_20200407_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('divisionname', models.CharField(max_length=64)),
                ('divisiondefinition', models.TextField(blank=True, null=True)),
                ('curated', models.BooleanField(blank=True, null=True)),
                ('published', models.BooleanField(blank=True, null=True)),
                ('record_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='recordsheet',
            name='workloadcovid',
        ),
        migrations.RemoveField(
            model_name='recordsheet',
            name='workloadidle',
        ),
        migrations.RemoveField(
            model_name='recordsheet',
            name='workloadother',
        ),
        migrations.AddField(
            model_name='recordsheet',
            name='recorddivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='covidskills.Division'),
        ),
    ]
